### ISSUE TITLE
Can't run a jobp from rest using /api/awa/run/v1/Activities?name=JOBP.ABC.1

### ISSUE THREAD

**Issue by imoussawit** [brendanSapience/UC4-Automic-REST-API-Delivery#3]
Hi,

Thanks for your work, it's incredible...

I have one problem, I can't launch a workflow using: 
/api/awa/run/v1/Activities?name=JOBP.ABC.1 
of the api. When I try, I get this error:
{"status":"error","message":"an error occured for operation run in version v1"}

My job is simple it's just a sleep of 60s in a bash command.

Best regards,

**Comment by brendanSapience** [comment]
hi,

strange.

how are you passing the authentication token? in the URL or as a header
parameter?

**Comment by imoussawit** [comment]
Hi, thanks for your answer.

I'm passing the token in the URL using &token=....  

All is working fine, stop, rerun... reading activities, all... 

But juste run is not working.

Best regards

**Comment by brendanSapience** [comment]
Ah yeah, this was an existing issue that was solved in the latest build.
Can you download the app again and check?

**Comment by imoussawit** [comment]
Ok, I will try. I don't remember when I didn't my rest install but, I don't think it was 1 month ago... 
When I download the war, I see that chrome put (1) on the file (UC4Rest-0.3-20170308-b1.war) because I already have the latest version...

But I will try to install it again.

Also there are 2 problems on the war, the dm-tools.jar is trying to write file in it's own folder, I had to uncompress it and remove the logback.xml file to be able to use it. the seconds is that logs are in debug mode... so in one week of usage, I had almost 10Gb of logs...

Best regards

**Comment by brendanSapience** [comment]
good point. the dm-tools.jar is actually being removed from the API (it allowed for the ARA specific calls, which are no longer necessary as automic provides now a native Rest API for ARA itself).

this will no longer be an issue in the next build.

thanks for letting me know!

**Comment by imoussawit** [comment]
Hi, I reinstall (and I check) I have the latest version ( UC4Rest-0.3-20170308-b1 ) installed.

I still have the problem, can I post the token ?

best regards

**Comment by brendanSapience** [comment]
I built a new binary just now (I removed the dm-tools.jar), so that problem should be taken care of.

I still cant reproduce the issue of trying to run the JOBP object.

It might be an Automic side problem im not accounting for in the rest api: can you send me an xml export of the JOBP and all the objects within the JOBP that you are trying to run?

thank you

**Comment by brendanSapience** [comment]
Also,

can you download the latest and try again (Build of taday: b2)?

the output you will get should at least tell us a bit more (it should give you a JSON response with a "details" field) => can you send that to me?

**Comment by imoussawit** [comment]
Hi thanks, I did install the b2 version.

I still get the problem but,  and I don't get a json back.. I'm getting an grail html page:
This is my request:
http://<server>/api/awa/run/v1/Activities?name=EXPTR.EXPTR.JOBP.GENER_FLUX_METRICS_IMO&token=8h2p6a2m1l8f2v5osultb04gl0

response: 
`<!DOCTYPE html>




 <html lang="en" class="no-js">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title>Error</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="shortcut icon" href="/automic-rest/assets/favicon-9ef27019cc7a636e29ecc851528f716e.ico" type="image/x-icon">
		<link rel="apple-touch-icon" href="/automic-rest/assets/apple-touch-icon-c915103363017d14cea9c2a46ea12166.png">
		<link rel="apple-touch-icon" sizes="114x114" href="/automic-rest/assets/apple-touch-icon-retina-21d524e96ee946f16c9b8fb4ea0c3f6e.png">
  		<link rel="stylesheet" href="/automic-rest/assets/application-3ae193875e14b4c750c49aae2285f4e5.css"/>
		<script src="/automic-rest/assets/application-03cdf070094eabaa419a61df4f9287af.js" type="text/javascript" ></script>
		
		
		<meta name="layout" content="main">
		
	
	</head>
	<body>
		<div id="grailsLogo" role="banner"><a href="http://grails.org"><img src="/automic-rest/assets/grails_logo-eabe4af98753b0163266d7e68bbd32e3.png" alt="Grails"/></a></div>
		
		
			<ul class="errors">
				<li>An error has occurred</li>
			</ul>
		
	
		<div class="footer" role="contentinfo"></div>
		<div id="spinner" class="spinner" style="display:none;">Loading&hellip;</div>
	</body>
</html>
`

**Comment by brendanSapience** [comment]
ah yeah, there was a small problem in the trace i implemented. Just fixed it. Couple of things tho:

- can you send me an XML export of the object you are trying to run? (also containing the objects within the workflow).

- can you provide the exact URL you are using to call the web service? (the one you provided is missing the hostname/port)

**Comment by imoussawit** [comment]
here is my url:
http://pral-opsrestautomic.workit.fr/api/awa/run/v1/Activities?name=EXPTR.EXPTR.JOBP.GENER_FLUX_METRICS_IMO&token=uo3nuofa34h1m6r97dgt1pqac5

Here are the xml that I export:
[JOBS.zip](https://github.com/brendanSapience/UC4-Automic-REST-API-Delivery/files/934250/JOBS.zip)

Best regards

(I did the last update and style the HTML error)

**Comment by brendanSapience** [comment]
Hi,

the URL is missing the app name for the webserver to resolve:

http://hostname/**APPNAME**/api/awa/run/v1/Activities?name=JOBP.SAMPLE

ex:

http://AETestHost:8080/**UC4Rest**/api/awa/run/v1/Activities?name=EXPTR.EXPTR.JOBP.GENER_FLUX_METRICS_IMO&token=MyToken

Also, the JOBS inside your JOBP seems to be assigned a HOST "HOSTG" which would be the Template Object. Which Client are you running this in?

**Comment by imoussawit** [comment]
There is no APPNAME, I put my tomcat behind an apache2 so I resolve directly the webservice with pral-opsrestautomic.workit.fr (it's working for everything else such as /rerunid or stop ... list.. activities and search...), I also try directly using the tomcat url but it didn't work..

We are using the automic java client... but the command is simple it's just a bash test with a  sleep of 120s..

Best regards

**Comment by brendanSapience** [comment]
What about the client number you are connecting to?

What host ate you using in the job? The export says HOSTG, which is a
template, is that normal?

Can you retry with the latest one?

**Comment by imoussawit** [comment]
HOSTG I think it's a host group... because it can be run on many linux servers (all clone of the first one)

I will retry today

**Comment by imoussawit** [comment]
![image](https://cloud.githubusercontent.com/assets/27220701/25265639/51ffb2a6-266e-11e7-88d5-24ea9a9443af.png)

Same result with direct contact with tomcat:
http://pral-opsrestautomic.workit.fr:8081/automic-rest/api/awa/run/v1/Activities?name=EXPTR.EXPTR.JOBP.GENER_FLUX_METRICS_IMO&token=uo3nuofa34h1m6r97dgt1pqac5

To launch manually I'm using:

![image](https://cloud.githubusercontent.com/assets/27220701/25265717/a980b188-266e-11e7-918c-c552d732f64f.png)

It's automic 10.3 (i think...)

**Comment by imoussawit** [comment]
When I'm using another function like search, it's working:
![image](https://cloud.githubusercontent.com/assets/27220701/25266006/ea795482-266f-11e7-9a7a-05333f71c720.png)

Url CALL:
http://pral-opsrestautomic.workit.fr:8081/automic-rest/api/awa/search/v1/Activities?filters=[name:EXPTR.EXPTR.JOBP.GENER_FLUX_METRICS_IMO]&token=uo3nuofa34h1m6r97dgt1pqac5

**Comment by imoussawit** [comment]
I try to make a wrong url, to check if the webservice is really responding:
![image](https://cloud.githubusercontent.com/assets/27220701/25266801/d25e2500-2672-11e7-827c-8d4df76d0931.png)

So yes, it's checking for arguments (I removed the "e" of name):
http://pral-opsrestautomic.workit.fr:8081/automic-rest/api/awa/run/v1/Activities?nam=EXPTR.EXPTR.JOBP.GENER_FLUX_METRICS_IMO&token=uo3nuofa34h1m6r97dgt1pqac5

**Comment by brendanSapience** [comment]
thank you for the details! it might be the version of AE. let me try to see if i can find a test system here to try to reproduce the issue.

**Comment by brendanSapience** [comment]
Bad news: i cant reproduce it with v10. i still have an error message because the object is using a HostGroup called HOSTG (which is a Client 0 template only and should not be used as is), so onsistent with v11 and v12 behavior:

{
  "status": "error",
  "message": "Invalid access rights for the client 0 AgentGroup 'HOSTG'.",
  "msgnumber": "5008"
}

can you try to change the Agent assignement to a regular agent, see if it makes a difference by any chance?

**Comment by brendanSapience** [comment]
Hi,

any news on this? did you manage to solve the issue?

**Comment by imoussawit** [comment]
Hi Brendan,

Sorry, I didn't have time to test an upgrade of automic.

For us it's still doesn't work. I'm working on many subject :)

We have a maintenance program but we didn't do the upgrade. My superior is thinking by doing it, soon but I don't know when.

Best regards.
